/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class milan_kapetanovic_memorygame_JNIExample */

#ifndef _Included_milan_kapetanovic_memorygame_JNIExample
#define _Included_milan_kapetanovic_memorygame_JNIExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     milan_kapetanovic_memorygame_JNIExample
 * Method:    racunajProcenat
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_milan_kapetanovic_memorygame_JNIExample_racunajProcenat
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
